### ISSUE TITLE
support Immutant

### ISSUE THREAD

**Issue by tobias** [dgrnbrg/spiral#13]
Immutant 2.x has an async model that is similar to http-kit, so writing an adapter was straightforward. I have it sitting on a branch right now (https://github.com/tobias/spiral/tree/immutant-support), since it depends on changes that will be in the next release of Immutant (which should be this week). Once that's out, I'll update that branch and submit a PR (assuming you are interested in receiving it :) ). I also have a fix for `route-concurrently` that is needed for the tests to pass with Immutant (parked at https://github.com/tobias/spiral/commit/9e23fdeba7553e104930b2118bb1bef354702853) that I'll also submit as a PR at the same time.

**Comment by dgrnbrg** [comment]
Yes, I'm definitely interested in the PR! That fix looks good.

**Comment by tobias** [comment]
Great! I'll come back for a visit once we release.

**Comment by dgrnbrg** [comment]
I think we now have solid support for Immutant. Thanks @tobias!

**Comment by tobias** [comment]
My pleasure!
